### PR TITLE
Add replacements for find-file-other-window and friends

### LINKED ISSUE #60: Support "other-window" functions (ones that start C-x 4)
`C-x 4 C-h` lists the following commands in my emacs:

```
C-x 4 C-f       find-file-other-window
C-x 4 C-o       display-buffer
C-x 4 .         xref-find-definitions-other-window
C-x 4 0         kill-buffer-and-window
C-x 4 a         add-change-log-entry-other-window
C-x 4 b         switch-to-buffer-other-window
C-x 4 c         clone-indirect-buffer-other-window
C-x 4 d         dired-other-window
C-x 4 f         find-file-other-window
C-x 4 m         compose-mail-other-window
C-x 4 r         find-file-read-only-other-window
```

It would be neat to write a wrapper that lets you select the "other window", then do one of these things. Looks like several applications of `switch-window--then`. I may try to put together a PR for this.

### PR DESCRIPTION
**Pull request by endgame**
Closes #60 . I don't know how to regenerate the README from the .el markup or what you want to do with version numbers etc. I leave that to you.

### CODE REVIEW

**Comment by tumashu** [comment]
1. Do not use helm*
2. Do not use lexical-let

**Comment by tumashu** [comment]
Maybe we should set lexical-binding to t in switch-window.el

**Comment by endgame** [comment]
That's up to you. I'm happy to drop back to standard `let`.

As for helm, it only uses those functions if they are bound. Any time a helm function is called there is a sensible fallback.

**Comment by endgame** [comment]
Removed `lexical-let`.

**Comment by tumashu** [comment]
is find-if a cl function? if it is, suggest use cl-find-if

**Comment by endgame** [comment]
`find-if` is an alias for `cl-find-if`.

**Comment by tumashu** [comment]
switch-window.el use cl-lib instead of cl, so it need cl- prefix

**Comment by endgame** [comment]
Will fix tonight. If you feel strongly about the helm stuff I can remove the fallback behaviour (and `find-if` calls etc), and just do that customisation in my personal config.

**Comment by tumashu** [comment]
just replace find-if to cl-find-if, as for helm, we can merge and try, if have other problem, fix again.

**Comment by tumashu** [comment]
Maybe we should support helm or counsel global in switch-window.el,  I merged and do this job.

**Comment by tumashu** [comment]
@endgame  using (setq switch-window-preferred 'helm)

**Comment by endgame** [comment]
I like what you've done. Thank you.

**Pull request merged**
