### PR TITLE
Add customizable key for minibuffer

### PR DESCRIPTION
**Pull request by SamHasler**

### CODE REVIEW

**Comment by dimitri** [comment]
Does this work with a layout of more than 10 windows in the current frame?

**Comment by SamHasler** [comment]
Oh bother I removed the "remove". I'd worked out how to do it. I'll fix it tomorrow.

**Comment by dimitri** [comment]
Thanks!

**Comment by SamHasler** [comment]
Still working on this, I think I can see how to make it a singe customize value now.

**Comment by SamHasler** [comment]
This is ready to merge now unless you'd like any changes.

**Comment by dimitri** [comment]
Looks good, thanks for putting in the extra effort and making it a reality! Can you please consider rebasing your branch so that I merge a single commit? Thanks

**Comment by SamHasler** [comment]
Ok. Can't do this via the github UI. I know how to do it on the command line but haven't got time to do it today or tomorrow so will try to rebase in a few days.

**Comment by dimitri** [comment]
Ok, will merge as soon as you get to it!

**Comment by tumashu** [comment]
@SamHasler is it this pull request status?

**Comment by tumashu** [comment]
see #34

**Pull request closed without merging**
