### PR TITLE
defalias `switch-to-window' to `switch-window-then-delete'

### PR DESCRIPTION
**Pull request by tumashu**

### CODE REVIEW

**Comment by dimitri** [comment]
I don't understand why `switch-to-window` should alias to *Delete window* action?

**Comment by tumashu** [comment]
I don not know, it is switch-window origin behaver

**Comment by tumashu** [comment]
sorry,  it is my fault, it should be delete-other-window....
```
(defun delete-other-window ()
  "Display an overlay in each window showing a unique key, then
ask user which window to delete"
  (interactive)
  (if (> (length (window-list)) 1)
      (progn
        (let ((index (prompt-for-selected-window "Delete window: ")))
          (apply-to-window-index 'delete-window index "")))))
```

**Comment by tumashu** [comment]
i will fix it later

**Pull request merged**
