### PR TITLE
*Big* refactor switch-window

### PR DESCRIPTION
**Pull request by tumashu**
switch-window is a very useful tool, i like it very much and use it frequently, 
This pull include big code refact, suggest include.

### CODE REVIEW

**Comment by tumashu** [comment]
by the way, switch-window will be an important tool for exwm (emacs X window manager)

**Comment by dimitri** [comment]
Hi!

Thanks for the effort here! Can you tell me more about why the refactoring (and incompatible changes in variable and config names)? Also, do you want to help maintain switch-window and have git push access here?

**Comment by tumashu** [comment]
The below is my reason:
1. "switch-window-" prefix not unique, it is too common and easy confuse people, for example:
     "switch-window-delete-window", no people can see "switch-window-" as a prefix.
2. "switch-window-" seemd too long.

**Comment by tumashu** [comment]
```
do you want to help maintain switch-window and have git push access here
```
I will send pull request to you if I have new code :-)

**Comment by dimitri** [comment]
I can't find the `switch-window-delete-window` function, where is it defined?

For code review, yes I would still like to be in the loop, it would allow you to fix bugs directly if you want to and to push to the repo once the review is done...

**Comment by tumashu** [comment]
switch-window-delete-window has been renamed to switchw-delete-window now

**Comment by tumashu** [comment]
```
For code review, yes I would still like to be in the loop, it would allow you to fix bugs directly if you want to and to push to the repo once the review is done...
```
Ok, no problem.

**Comment by dimitri** [comment]
I had the impression that other packages would define functions using the same `switch-window-` prefix as we do, hence causing confusion. If that's not the case, then I think we should continue using that `switch-window-` prefix even if it's quite long: it makes things obvious, and I like that.

**Comment by tumashu** [comment]
If you like "switch-window-" prefix, just stay it, although "switchw-" is a good prefix too :-)

**Comment by tumashu** [comment]
If we use "switch-window-" prefix, I think "switch-window-delete-window" and  "switch-window-maximize-window" two command names are too agly, need find two new names

**Comment by dimitri** [comment]
Long function names are helping to show the intention of the code, which is difficult to convey, and so for me there's no problem with very long names in the code, as you see. And yes I prefer the `switch-window-` prefix, if only for backwards compatibility with existing users.

**Comment by tumashu** [comment]
OK, please review again...

**Comment by dimitri** [comment]
Thanks, feel free to merge (well I didn't test it, I trust you that all that worked before still does).

**Comment by tumashu** [comment]
OK

**Pull request merged**
