### PR TITLE
(WIP) Minibuffer is always "0"

### PR DESCRIPTION
**Pull request by SamHasler**

### CODE REVIEW

**Comment by SamHasler** [comment]
# Don't pull this!

It's broken every key execpt "0"

I'll try and fix it this week.

**Comment by dimitri** [comment]
If you can also make this feature optional and off by default it would be great, thanks!

**Comment by SamHasler** [comment]
Ok. Will see what I can do.

Any idea how I broke non-"0" inputs? It's got me flummoxed.

**Comment by SamHasler** [comment]
Found a tidier way of doing it with customization, will submit a new clean pull request.

**Pull request closed without merging**
