### PR TITLE
Add variable: switch-window-input-style

### PR DESCRIPTION
**Pull request by tumashu**
Switch-window use read-event to read users input by default, it will
be conflicted with EXWM (Emacs X window manager), So I add a new
input style: 'minibuffer to handle this issue.

The origin input style is named as 'default, the intuitive different
is that: 'minibuffer style need to "confirm" your input with Enter.

### CODE REVIEW

**Comment by tumashu** [comment]
Now, the two input style have same behaver, so user can select any one to use. no need to type "Return" to confirm again ;-)

**Comment by tumashu** [comment]
```
 	Add variable: switch-window-label-buffer-function
```

This commit add a feature to solve this issue: https://github.com/dimitri/switch-window/pull/39
but user can do more, for example: using picture as label with the help of iimage-mode

**Comment by tumashu** [comment]
I will merge the PR, if have problem, I will fix it later with new PR :-)

**Comment by dimitri** [comment]
Congrats @tumashu; this project is now in very good hands ;-)

**Comment by tumashu** [comment]
Because switch-window is an important tool for me :-)

**Pull request merged**
